var translations = {};

translations["lt"] = {
  "new_program": "Nauja programa",
  "run_program": "Vykdyti",
  "run_tests": "Vertinti",
  "stop_it": "Stabdyti",
  "clear_output": "Išvalyti išvestį",
  "upload_program": "Įkelti",
  "download_program": "Atsisiųsti",
  "input_button": "Pateikti",
  "console_output": "Išvestis",
  "testing": "Testavimas",
  "test_data": "Testo duomenys",
  "console_result": "Konsolės rezultatas",
  "overall_result": "Bendras rezultatas",
  "correct": "Teisingai",
  "incorrect": "Neteisingai",
  "start_over": "Ar tikrai norite startuoti iš naujo?",
  "Files_string" : "Failai",
  "Examples" : "Pavyzdžiai",
  "true_content_not_allowed" : "Testo kūrėjas neleidžia pamatyti šios testo dalies.",
  "true_result" : "Teisingi rezultatai",
  "not_displayed" : "Nerodoma",
  "congrats" : "<strong>Sveikinimai! Jums pavyko!</strong>",
  "losing" : "<strong>Deja, Jums nepavyko...</strong>",
  "required" : "Reikėjo: ",
  "acquired" : "Surinkote: ",
  "ok_button" : "Gerai",
  "drop_acquired" : "<b>Dėmesio!</b> Jūs gavote numestuką!",
  "hints_text" : "Užuominos",
  "open_hint" : "Atverti užuominą",
  "request_explanation" : "Paaiškink",
  "request_correction" : "Pataisyk",
  "request_review" : "Atsiliepimas",
  "string_comparison" : "Eilučių palyginimas",
  "compare_strings" : "Palyginti",
  "compare_files" : "Palyginti"
};

translations["pl"] = {
  "new_program": "Nowy program",
  "run_program": "Uruchom",
  "run_tests": "Evaluate",
  "stop_it": "Stop",
  "clear_output": "Wyczyść dane wyjściowe",
  "upload_program": "Prześlij",
  "download_program": "Pobierz",
  "input_button": "Submit",
  "console_output": "Wyjście",
  "testing": "Testing",
  "test_data": "Dane testowe",
  "console_result": "Wynik konsoli",
  "overall_result": "Wynik ogólny",
  "correct": "Prawidłowy",
  "incorrect": "Niepoprawny",
  "start_over": "Czy na pewno chcesz uruchomić ponownie?",
  "Files_string" : "Pliki",
  "Examples" : "Przykłady",
  "true_content_not_allowed" : "Twórca testu nie pozwala na wyświetlenie tej części testu.",
  "true_result" : "Prawidłowe wyniki",
  "not_displayed" : "Nie dotyczy",
  "congrats" : "<strong>Gratulacje! Udało ci się!</strong>",
  "losing" : "<strong>Niestety nie...</strong>",
  "required" : "Potrzebowałeś: ",
  "acquired" : "Znalazłeś: ",
  "ok_button" : "Ok",
  "drop_acquired" : "<b>Uwaga! </b> Zdobyłeś spadek!",
  "hints_text" : "Wskazówki",
  "open_hint" : "Otwórz wskazówkę",
  "request_explanation" : "Wyjaśnij",
  "request_correction" : "Popraw",
  "request_review" : "Referencje",
  "string_comparison" : "Porównanie linii",
  "compare_strings" : "Porównaj",
  "compare_files" : "Porównaj"
}

translations["en"] = {
  "new_program": "New program",
  "run_program": "Run",
  "run_tests": "Evaluate",
  "stop_it": "Stop",
  "clear_output": "Clear output",
  "upload_program": "Upload",
  "download_program": "Download",
  "input_button": "Submit",
  "console_output": "Output",
  "testing": "Testing",
  "test_data": "Test data",
  "console_result": "Console result",
  "overall_result": "Overall result",
  "correct": "Correct",
  "incorrect": "Incorrect",
  "start_over": "Are you sure you want to restart?",
  "Files_string" : "Files",
  "Examples" : "Examples",
  "true_content_not_allowed" : "The test developer does not allow you to see this part of the test.",
  "true_result" : "Correct results",
  "not_displayed" : "Not displayed",
  "congrats" : "<strong>Congratulations! You did it!</strong>",
  "losing" : "<strong>Unfortunately, you have failed...</strong>",
  "required" : "Points required: ",
  "acquired" : "Points avquired: ",
  "ok_button" : "Ok",
  "drop_acquired" : "<b>Attention!</b> You acquired a drop!",
  "hints_text" : "Hints",
  "open_hint" : "Open hint",
  "request_explanation" : "Explain",
  "request_correction" : "Correct",
  "request_review" : "Review",
  "string_comparison" : "String comparison",
  "compare_strings" : "Compare",
  "compare_files" : "Compare"
};